# Generated by Django 4.1 on 2022-08-29 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(max_length=255, verbose_name='Температура.')),
                ('feels_like', models.IntegerField(max_length=255, verbose_name='Ощущаемая температура.')),
                ('temp_water', models.IntegerField(max_length=255, verbose_name='Температура воды.')),
                ('icon', models.CharField(max_length=255, verbose_name='Код иконки погоды. Иконка доступна по адресу https://yastatic.net/weather/i/icons/funky/dark/<значение из поля icon>.svg.')),
                ('condition', models.CharField(max_length=255, verbose_name='Код расшифровки погодного описания')),
                ('phenom_condition', models.CharField(max_length=255, verbose_name='Код расшифровки дополнительного погодного описания.')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField(max_length=255, verbose_name='Широта (в градусах).')),
                ('lon', models.IntegerField(max_length=255, verbose_name='Долгота (в градусах).')),
                ('offset', models.IntegerField(max_length=255, verbose_name='Часовой пояс в секундах от UTC.')),
                ('name', models.CharField(max_length=255, verbose_name='Название часового пояса.')),
                ('abbr', models.CharField(max_length=255, verbose_name='Сокращенное название часового пояса.')),
                ('dst', models.BooleanField(verbose_name='Признак летнего времени.')),
                ('def_pressure_mm', models.IntegerField(max_length=255, verbose_name='Норма давления для данной координаты (в мм рт. ст.).')),
                ('def_pressure_pa', models.IntegerField(max_length=255, verbose_name='Норма давления для данной координаты (в гектопаскалях).')),
                ('url', models.CharField(max_length=255, verbose_name='Страница населенного пункта на сайте Яндекс.Погода')),
            ],
        ),
        migrations.CreateModel(
            name='Time_zone_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.IntegerField(max_length=255, verbose_name='Часовой пояс в секундах от UTC')),
                ('name', models.CharField(max_length=255, verbose_name='Название часового пояса.')),
                ('abbr', models.CharField(max_length=255, verbose_name='Сокращенное название часового пояса.')),
                ('dst', models.BooleanField(verbose_name='Признак летнего времени')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('now', models.IntegerField(max_length=255, verbose_name='Время сервера в формате Unixtime.')),
                ('now_dt', models.CharField(max_length=255, verbose_name='Время сервера в UTC.')),
                ('fact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.fact', verbose_name='Фактической информации о погоде.')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.info', verbose_name='Информации о населенном пункте.')),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='tz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.time_zone_info', verbose_name='Информация о часовом поясе.'),
        ),
    ]
