# Generated by Django 4.1 on 2022-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='abbr',
            field=models.CharField(max_length=255, null=True, verbose_name='Сокращенное название часового пояса.'),
        ),
        migrations.AlterField(
            model_name='info',
            name='def_pressure_mm',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Норма давления для данной координаты (в мм рт. ст.).'),
        ),
        migrations.AlterField(
            model_name='info',
            name='def_pressure_pa',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Норма давления для данной координаты (в гектопаскалях).'),
        ),
        migrations.AlterField(
            model_name='info',
            name='dst',
            field=models.BooleanField(null=True, verbose_name='Признак летнего времени.'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lat',
            field=models.IntegerField(null=True, verbose_name='Широта (в градусах).'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lon',
            field=models.IntegerField(null=True, verbose_name='Долгота (в градусах).'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название часового пояса.'),
        ),
        migrations.AlterField(
            model_name='info',
            name='offset',
            field=models.IntegerField(null=True, verbose_name='Часовой пояс в секундах от UTC.'),
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='Страница населенного пункта на сайте Яндекс.Погода'),
        ),
    ]
