# Generated by Django 4.1 on 2022-08-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_info_abbr_alter_info_def_pressure_mm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='abbr',
        ),
        migrations.RemoveField(
            model_name='info',
            name='dst',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='offset',
        ),
        migrations.AlterField(
            model_name='fact',
            name='condition',
            field=models.CharField(max_length=255, null=True, verbose_name='Код расшифровки погодного описания'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='feels_like',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Ощущаемая температура.'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='icon',
            field=models.CharField(max_length=255, null=True, verbose_name='Код иконки погоды. Иконка доступна по адресу https://yastatic.net/weather/i/icons/funky/dark/<значение из поля icon>.svg.'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='phenom_condition',
            field=models.CharField(max_length=255, null=True, verbose_name='Код расшифровки дополнительного погодного описания.'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='temp',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Температура.'),
        ),
        migrations.AlterField(
            model_name='fact',
            name='temp_water',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Температура воды.'),
        ),
        migrations.AlterField(
            model_name='time_zone_info',
            name='abbr',
            field=models.CharField(max_length=255, null=True, verbose_name='Сокращенное название часового пояса.'),
        ),
        migrations.AlterField(
            model_name='time_zone_info',
            name='dst',
            field=models.BooleanField(null=True, verbose_name='Признак летнего времени'),
        ),
        migrations.AlterField(
            model_name='time_zone_info',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название часового пояса.'),
        ),
        migrations.AlterField(
            model_name='time_zone_info',
            name='offset',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Часовой пояс в секундах от UTC'),
        ),
    ]
