# Generated by Django 4.1 on 2022-08-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_fact_feels_like_alter_fact_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fact',
            name='phenom_condition',
        ),
        migrations.RemoveField(
            model_name='fact',
            name='temp_water',
        ),
    ]
