# Generated by Django 4.1 on 2022-08-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_requset_client_info_weather_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requset_client_info',
            name='ip',
            field=models.GenericIPAddressField(null=True, verbose_name='iP адрес клиент'),
        ),
    ]
